<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_OrangeWebUsingKeywords</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-01-08T11:16:41</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>caeb25e5-4cd8-48c8-9012-e377735a9b51</testSuiteGuid>
   <testCaseLink>
      <guid>1eed5b07-c68f-4a8c-abc1-967367dd34cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Orange_Website_Using_Function/Tc_TestOrangeWebUsingKeywords</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>84fccdad-8eee-438e-ad26-fb228578530b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestKeywords/Data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>84fccdad-8eee-438e-ad26-fb228578530b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>c909138e-c135-43a1-bce1-56277cecc932</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>84fccdad-8eee-438e-ad26-fb228578530b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>b5df670f-63bf-48e5-b185-99290914add4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69ac5a8a-0633-43da-8dc3-16b1577b3f2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Orange_Website_Using_Function/TC_LoginKeyword</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>08c57d5d-c39e-461a-af4d-c167215a6764</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Orange_Website_Using_Function/TC_AllPageComponent</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d3572eb7-287a-46d0-a41d-9793a0daefef</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestKeywords/AllDataComponent</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d3572eb7-287a-46d0-a41d-9793a0daefef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CandidateName</value>
         <variableId>1077ebfd-d7fe-438e-8160-df1a38f34422</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d3572eb7-287a-46d0-a41d-9793a0daefef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobTitle</value>
         <variableId>a52c49ac-a01f-46dc-91d6-4c3a446f87ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d3572eb7-287a-46d0-a41d-9793a0daefef</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>WelcomeAdmin</value>
         <variableId>e7bd51c4-aeb5-439a-b30a-1466af2e6f9e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
