<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Login</name>
   <tag></tag>
   <elementGuidId>cb2dee7d-9adf-4714-9713-9bcf47bca0c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-login/div/div/div/div/div[2]/form/fieldset/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-login/div/div/div/div/div[2]/form/fieldset/div/button/span</value>
   </webElementProperties>
</WebElementEntity>
