<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Insert</name>
   <tag></tag>
   <elementGuidId>d98bbc87-4332-4408-bc8a-1f4332595d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-receivers-channels-layout/div/div[2]/div/app-receiver-list/div/div/p-datatable//div[1]/p-header//button/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-receivers-channels-layout/div/div[2]/div/app-receiver-list/div/div/p-datatable//div[1]/p-header//button/span[2]</value>
   </webElementProperties>
</WebElementEntity>
