<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BTN_Search</name>
   <tag></tag>
   <elementGuidId>486b9347-e28e-4998-ba83-c2a2b36a14ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-receivers-channels-layout/div/div[1]/div/app-receiver-search-fields/div/div/div/button[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app-form&quot;]/div/app-body/div/div/div[2]/div[2]/app-receivers-channels-layout/div/div[1]/div/app-receiver-search-fields/div/div/div/button[1]/span</value>
   </webElementProperties>
</WebElementEntity>
