<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MSG_SuccessValidationMessage</name>
   <tag></tag>
   <elementGuidId>95615b3b-bff2-4ce3-a300-db73a9e64eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;frmList_ohrmListComponent&quot;]/script</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;frmList_ohrmListComponent&quot;]/script</value>
   </webElementProperties>
</WebElementEntity>
