<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MNUITM_Recruitment</name>
   <tag></tag>
   <elementGuidId>85c0a5e4-295a-4d75-827e-42df4e1def51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;menu_recruitment_viewRecruitmentModule&quot;]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;menu_recruitment_viewRecruitmentModule&quot;]/b</value>
   </webElementProperties>
</WebElementEntity>
